## preprocess spatial data
## the input is the spatial folder path generated by spaceranger
## the output is a Seurat object (spatialobj) containing spatial data

library(Seurat)
library(dplyr)

spatialobj<-Load10X_Spatial("/spatial/path/to/data/directory",slice="S1")
spatialobj<-NormalizeData(spatialobj) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA() %>% RunUMAP(dims=1:30) %>% FindNeighbors() %>% FindClusters()


##cell type deconvolution 
##the input parameters are ss and spatialobj

##ss is the Seurat object containing single-cell RNAseq data with cell type annotation (anno)
##spatialobj is the Seurat object containing spatial data


library(spacexr)

#prepare the reference
counts<-GetAssayData(ss,slot="counts")
cell_types<-ss$anno
cell_types<-as.factor(cell_types)
nUMI<-colSums(counts)
reference<-Reference(counts,cell_types,nUMI)

#prepare the spatial data
counts<-GetAssayData(spatialobj,assay="Spatial",slot="counts")
coords<-GetTissueCoordinates(spatialobj)
nUMI<-colSums(counts)
puck<-SpatialRNA(coords,counts,nUMI)

#cell type deconvolution
myRCTD<-create.RCTD(puck,reference,max_cores=4)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'full')

#save the deconvolution result to the spatialobj
spatialobj@misc$RCTD<-myRCTD
spatialobj@misc$weights<-myRCTD@results$weights


##predict cell-type interaction###
##the input parameters are CTpair and spatialobj
## CTpair is a list that includes all cell-type pairs
##spatialobj is the Seurat object containing spatial data

library(SpaGene)
library(Matrix)

##normalize cell type composition to 1
ctinfo<-spatialobj@misc$weights
ctinfo<-sweep(ctinfo, 1, rowSums(ctinfo), "/")

##generate a new Seurat object containing the cell type deconvolution result

#match the spot
ind<-match(colnames(spatialobj),rownames(ctinfo))
newobj<-spatialobj[,!is.na(ind)]

tmpassay<-CreateAssayObject(t(ctinfo))
newobj[["RCTD"]]<-tmpassay

##predict cell-type interaction using SpaGene
expr<-GetAssayData(newobj,assay="RCTD")
location<-GetTissueCoordinates(tmpobj)
x<-SpaGene_LR(expr,location, normalize = F, LRpair=CTpair)

##save the cell-type interaction result to the spatialobj
spatialobj@misc$CT_CT<-x[order(x$adjp),]